name: Azure OIDC Authentication

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Request OIDC token
      contents: read  # Allow reading repo content 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: "a002c09f-553c-421b-a8af-86f435f69480"
          tenant-id: "1f4beacd-b7aa-49b2-aaa1-b8525cb257e0"
          subscription-id: "5dfb4d57-e8e3-4bb5-8cec-d6857c3f385b"
          identity: true  # Use OIDC

      - name: Deploy to Azure
        run: |
          # Your Azure deployment commands go here
          az group create -l westus -n MyResourceGroup
